base:
  project_id : 5
  project_name : insurance-prediction-pyspark
  version : 1.0
  description : "It will predict based on the insurance related things whether you get the insurance or not, based on the independent features, to overcome the risk of big data I created it with the help of pyspark"
  author : vicky
  license: MIT
  random_state : 42
  test_size : 0.2
mongodb_credentials_from_env_variables :
  user_name : MONGO_USER
  user_password: MONGO_PASSWORD
database_logs:
  training_logs: 
    database_name: insurance_training_logs
  prediction_logs: 
    database_name: insurance_prediction_logs

